baseURL = "https://tanner-mcgrath.me"
languageCode = "en-us"
title = "Techy Tanner"
theme = "congo"
timeZone = "America/New_York"

enableRobotsTXT = true

# Congo requires this for proper taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[params]
  colorScheme = "ocean"
  defaultAppearance = "dark"
  autoSwitchAppearance = true
  
  enableSearch = true
  enableCodeCopy = true
  
  [params.homepage]
    layout = "profile"
    homepageImage = ""
    showRecent = false

  [params.article]
    showDate = true
    showDateUpdated = false
    showAuthor = true
    showReadingTime = true
    showTableOfContents = true
    showTaxonomies = true
    showWordCount = false
    showSummary = true
    sharingLinks = ["twitter", "linkedin", "reddit", "email"]

  [params.list]
    showBreadcrumbs = true
    showSummary = true
    showTableOfContents = false
    groupByYear = true

  [params.author]
    name = "Tanner McGrath"
    headline = "Tech Enthusiast & Builder"
    bio = "Building things that matter."
    links = [
      { github = "https://github.com/tanner-malt" },
      { linkedin = "https://www.linkedin.com/in/tanner-mcgrath-aa6aa0228" },
      { kaggle = "https://www.kaggle.com/tannermcgrathlol" },
      { email = "mailto:tanner@tanner-mcgrath.me" }
    ]

[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pageRef = "blog"
    weight = 2
  [[menu.main]]
    name = "About"
    pageRef = "about"
    weight = 3
  [[menu.main]]
    name = "Now"
    pageRef = "now"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
